<?php

/**
 * @file
 * Hooks for the Glossary Tooltip module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_alter().
 */
function glossary_tooltip_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() !== 'node') {
    return;
  }

  /** @var \Drupal\glossary_tooltip\GlossaryTooltipProcessor $processor_service */
  $processor_service = \Drupal::service('glossary_tooltip.processor');

  if ($processor_service->alterBuild($build)) {
    $build['#attached']['library'][] = 'glossary_tooltip/frontend';
  }
}
