<?php

declare(strict_types=1);

/**
 * @file
 * Install hooks for the Glossary Tooltip module.
 */

use Drupal\taxonomy\Entity\Vocabulary;

/**
 * Implements hook_install().
 */
function glossary_tooltip_install() {
  if (!Vocabulary::load('glossary')) {
    $glossary_vocabulary = Vocabulary::create([
      'vid' => 'glossary',
      'name' => 'Glossary',
      'description' => 'Vocabulary used by the Glossary Tooltip module.',
    ]);
    $glossary_vocabulary->save();
  }
}
