<?php

/**
 * @file
 * Install hooks for the Glossary Tooltip module.
 */

use Drupal\taxonomy\Entity\Vocabulary;

/**
 * Implements hook_install().
 */
function glossary_tooltip_install() {
  if (!Vocabulary::load('glossary')) {
    $vocabulary = Vocabulary::create([
      'vid' => 'glossary',
      'name' => 'Glossary',
      'description' => 'Vocabulary used by the Glossary Tooltip module.',
    ]);
    $vocabulary->save();
  }
}
