name: Drupal CS

on:
  push:
  pull_request:

jobs:
  drupal-cs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull Drupal CS image
        run: docker pull timtom6891/drupal-cs:latest

      - name: Composer Normalize
        run: |
          docker run --rm \
            --volume "$GITHUB_WORKSPACE:/workspace" \
            --workdir /workspace \
            timtom6891/drupal-cs:latest \
            composer-normalize --dry-run /workspace/composer.json

      - name: PHPCS
        run: |
          docker run --rm \
            --volume "$GITHUB_WORKSPACE:/workspace" \
            --workdir /workspace \
            timtom6891/drupal-cs:latest \
            phpcs --standard=phpcs.xml
